[target.mips-unknown-linux-musl]
linker = "/home/david/openwrt-sdk-21.02.3-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/bin/mips-openwrt-linux-gcc"

[env]
CC_mips-unknown-linux-musl = { value = "/home/david/openwrt-sdk-21.02.3-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/bin/mips-openwrt-linux-gcc", forced = true }
MIPS_UNKNOWN_LINUX_MUSL_OPENSSL_DIR = { value = "/home/david/openwrt-sdk-21.02.3-ath79-generic_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl/", forced = true }
# CROSS_COMPILE = { value = "mips-openwrt-linux-musl", force = true }
